### ISSUE TITLE
Usage with gradle Kotlin DSL (add instructions)

### ISSUE THREAD

**Issue by AntonPieper** [mozilla/rust-android-gradle#128]
Modern android applications use [Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) instead of groovy for the gradle scripts. Also they use [`libs.versions.toml`](https://developer.android.com/build/migrate-to-catalogs). I tried to migrate to these, however it does not work. Could you ad instructions on how to add this plugin using Kotlin DSL and `libs.versions.toml`?

**Comment by AntonPieper** [comment]
Ok, it actually was really simple:

**`build.gradle.kts`** _(in :app)_
```kts
@Suppress("DSL_SCOPE_VIOLATION") // TODO: Remove once KTIJ-19369 is fixed
plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.rust)
}

cargo {
    module  = "../rust"       // Or whatever directory contains your Cargo.toml
    libname = "rust"          // Or whatever matches Cargo.toml's [package] name.
    targets = listOf("arm", "x86")  // See bellow for a longer list of options
}
```

**`libs.versions.toml`**
```toml
[versions]
rust = "0.9.3"

[plugins]
rust = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rust" }

```
