### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libgit_wrapper.so" not found

### ISSUE THREAD

**Issue by wiiznokes** [mozilla/rust-android-gradle#165]
I get this error but i don't know why.

This is my Cargo.toml:

```toml
[package]
name = "git_wrapper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
```

build.gradle.kts:

```kt
cargo {
    module  = "./src/main/rust"
    libname = "git_wrapper"
    targets = listOf("arm64", "x86_64")
}

tasks.whenTaskAdded {
    if (name == "javaPreCompileDebug" || name == "javaPreCompileRelease") {
        dependsOn("cargoBuild")
    }
}
```

And in kotlin: `System.loadLibrary("git_wrapper")`.

`app/src/main/rust/target/aarch64-linux-android/debug/libgit_wrapper.so` and `app/src/main/rust/target/x86_64-linux-android/debug/libgit_wrapper.so` exists, and seems to be included as jni files

![Image](https://github.com/user-attachments/assets/93c1571e-6a8a-43d9-af9d-256fe7690a83)

idk what to do, any help appreciated, ty!
